vpc_name = "elk-project-vpc"
private_subnet_name = "elk-private"
public_subnet_name =  "elk-public"
ubuntu_version = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
ami_owner = "099720109477"
# LOGSTASH_IP = "$LOGSTASH_IP"